---

# Required for Java 1.8
- name: install jessie-backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
  when: ansible_distribution_release == 'jessie'

- name: install Minecraft dependencies
  apt:
    name: "{{ dependencies }}"
    state: present
    install_recommends: false
    default_release: "{{ (ansible_distribution_release == 'jessie') | ternary('jessie-backports', omit) }}"

- name: install Spigot dependencies
  apt:
    name: ['git', 'tar']
  when: minecraft_server_type == 'spigot'
