---

- name: Update apt cache.
  apt:
    update_cache: true
    cache_valid_time: 600
  when: ansible_os_family == 'Debian'
  changed_when: false
  become: true

# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
- name: Ensure 'man' directory exists.
  file:  # noqa 208
    path: /usr/share/man/man1
    state: directory
    recurse: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 18

- name: install Minecraft dependencies
  apt:
    name: "{{ dependencies }}"
    state: present
    install_recommends: false
    update_cache: true
    default_release: "{{ (ansible_distribution_release == 'jessie') | ternary('jessie-backports', omit) }}"

- name: install Spigot dependencies
  apt:
    name: ['git', 'tar']
  when: minecraft_server_type == 'spigot'
