---

- name: build Spigot server
  command: "java -jar BuildTools.jar --rev {{ minecraft_version_latest | default(minecraft_version) }}"
  args:
    creates: "spigot-{{ minecraft_version_latest | default(minecraft_version) }}.jar"
    chdir: "{{ minecraft_home }}/build"
  environment:
    SHELL: /bin/bash
  become: true
  become_user: "{{ minecraft_user }}"
  changed_when: false

- name: Find new spigot jar file
  shell: ls -r spigot-* | head -1
  args:
    chdir: "{{ minecraft_home }}/build"
  register: spigot_file
  changed_when: false

- name: symlink Spigot server
  file:
    src: "{{ minecraft_home }}/build/{{ spigot_file.stdout }}"
    path: "{{ minecraft_home }}/spigot.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
  become: true
  notify:
    - restart Minecraft

- name: agree to EULA
  copy:
    src: eula.txt
    dest: "{{ minecraft_home }}/eula.txt"
    mode: 0644
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - enable service
